import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header>
        <nav className="navbar">
          <Link href="/" className=" px-4 text-xl font-semibold">
            Taskbored
          </Link>
        </nav>
      </header>
      <main>{children}</main>
    </>
  );
}
