import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="navbar">
            <Link href="/home">Logo</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
