import NavBar from "@/components/Home/NavBar";
import Footer from "@/components/Home/Footer";

export const metadata = {
  title: "Taskbored",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=" mx-auto max-w-7xl">
      <NavBar />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
