import NavBar from "@/components/Home/NavBar";
import { AuthProvider } from "@/contexts/AuthContext";

export const metadata = {
  title: "Taskbored",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <main>{children}</main>
    </>
  );
}
