import NavBar from "~/components/Home/NavBar";
import Footer from "~/components/Home/Footer";
import { Outlet } from "@remix-run/react";

export const meta = () => {
  return [
    { title: "Taskbored" },
    { description: "Generated by create next app" },
  ];
};

export default function HomeLayout() {
  return (
    <div className=" mx-auto max-w-7xl">
      <NavBar />
      <main>
        <Outlet />
      </main>
      <Footer />
    </div>
  );
}
