import NavBar from "~/components/home/NavBar";
import Footer from "~/components/home/Footer";
import { Outlet } from "@remix-run/react";
import { type LoaderFunction, redirect } from "@remix-run/node";
import { getAuth } from "@clerk/remix/ssr.server";

export const meta = () => {
  return [
    { title: "Taskbored" },
    { description: "Generated by create next app" },
  ];
};

export const loader: LoaderFunction = async (args) => {
  const { userId } = await getAuth(args);
  if (userId) {
    return redirect("/app/today");
  }
  return {};
};

export default function HomeLayout() {
  return (
    <>
      <NavBar />
      <main className="mx-auto max-w-7xl">
        <Outlet />
      </main>
      <Footer />
    </>
  );
}
